"""initial schema

Revision ID: 1ec67db47ee0
Revises: 
Create Date: 2026-08-04 10:38:12.495299
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types (JSONColumn, TZDateTime, BigIntPK, MoneyColumn) are
# rendered by autogenerate as fully-qualified names, so the module must be
# importable from the migration itself.
import forecaster.db.types
import forecaster.db.types

revision: str = '1ec67db47ee0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quota',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('window_start', forecaster.db.types.TZDateTime(), nullable=False),
    sa.Column('limit_per_window', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('feature_sets',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('spec', forecaster.db.types.JSONColumn, nullable=False),
    sa.Column('created_at', forecaster.db.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_feature_set')
    )
    op.create_table('ingestion_log',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('started_at', forecaster.db.types.TZDateTime(), nullable=True),
    sa.Column('finished_at', forecaster.db.types.TZDateTime(), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_log_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_log_symbol'), ['symbol'], unique=False)

    op.create_table('instruments',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('ipo_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('created_at', forecaster.db.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', forecaster.db.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index('idx_instruments_name', ['name'], unique=False)
        batch_op.create_index('idx_instruments_tier_active', ['tier', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_symbol'), ['symbol'], unique=True)
        batch_op.create_index(batch_op.f('ix_instruments_tier'), ['tier'], unique=False)

    op.create_table('macro_series',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('units', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('universes',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corporate_actions',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'ex_date', 'action_type', name='uq_corp_action')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('fundamentals',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'fiscal_period')
    )
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fundamentals_report_date'), ['report_date'], unique=False)

    op.create_table('macro_observations',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['macro_series.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code', 'ts')
    )
    op.create_table('model_runs',
    sa.Column('id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('universe_id', sa.BigInteger(), nullable=True),
    sa.Column('feature_set_id', sa.BigInteger(), nullable=True),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('horizon_days', sa.SmallInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('hyperparams', forecaster.db.types.JSONColumn, nullable=False),
    sa.Column('split_config', forecaster.db.types.JSONColumn, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('started_at', forecaster.db.types.TZDateTime(), nullable=True),
    sa.Column('finished_at', forecaster.db.types.TZDateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', forecaster.db.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index('idx_runs_lookup', ['instrument_id', 'model_name', 'horizon_days', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_status'), ['status'], unique=False)

    op.create_table('news_articles',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('published_at', forecaster.db.types.TZDateTime(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('scored_at', forecaster.db.types.TZDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index('idx_news_lookup', ['instrument_id', 'published_at'], unique=False)

    op.create_table('ohlcv_daily',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ingested_at', forecaster.db.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('high >= low AND high >= open AND high >= close AND low <= open AND low <= close AND volume >= 0 AND close > 0', name='ck_ohlcv_sane'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'ts')
    )
    with op.batch_alter_table('ohlcv_daily', schema=None) as batch_op:
        batch_op.create_index('idx_ohlcv_ts', ['ts'], unique=False)

    op.create_table('ohlcv_intraday',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', forecaster.db.types.TZDateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'ts')
    )
    op.create_table('universe_members',
    sa.Column('universe_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.Date(), nullable=False),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('universe_id', 'instrument_id', 'added_at')
    )
    op.create_table('backtest_runs',
    sa.Column('id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('model_run_id', forecaster.db.types.UUIDColumn, nullable=True),
    sa.Column('strategy_name', sa.String(length=60), nullable=False),
    sa.Column('config', forecaster.db.types.JSONColumn, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('initial_capital', forecaster.db.types.MoneyColumn, nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('calmar', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('n_trades', sa.Integer(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('total_costs', forecaster.db.types.MoneyColumn, nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('benchmark_sharpe', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('created_at', forecaster.db.types.TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_model_run_id'), ['model_run_id'], unique=False)

    op.create_table('feature_importance',
    sa.Column('run_id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('feature_name', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'feature_name', 'method')
    )
    op.create_table('fold_metrics',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('run_id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('fold_index', sa.SmallInteger(), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('test_start', sa.Date(), nullable=True),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('n_train', sa.Integer(), nullable=True),
    sa.Column('n_test', sa.Integer(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mase', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('directional_accuracy', sa.Float(), nullable=True),
    sa.Column('mcc', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('brier', sa.Float(), nullable=True),
    sa.Column('skill_vs_naive', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'fold_index', name='uq_fold')
    )
    with op.batch_alter_table('fold_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fold_metrics_run_id'), ['run_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('run_id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('fold_index', sa.SmallInteger(), nullable=True),
    sa.Column('is_out_of_sample', sa.Boolean(), nullable=False),
    sa.Column('y_pred', sa.Float(), nullable=False),
    sa.Column('y_pred_lower', sa.Float(), nullable=True),
    sa.Column('y_pred_upper', sa.Float(), nullable=True),
    sa.Column('prob_up', sa.Float(), nullable=True),
    sa.Column('y_true', sa.Float(), nullable=True),
    sa.CheckConstraint('target_date > as_of_date', name='ck_pred_is_forward_looking'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'instrument_id', 'as_of_date', 'target_date', name='uq_pred')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('idx_pred_lookup', ['instrument_id', 'target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_run_id'), ['run_id'], unique=False)

    op.create_table('run_metrics',
    sa.Column('run_id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('metrics', forecaster.db.types.JSONColumn, nullable=False),
    sa.Column('skill_vs_naive', sa.Float(), nullable=True),
    sa.Column('dm_stat', sa.Float(), nullable=True),
    sa.Column('dm_pvalue', sa.Float(), nullable=True),
    sa.Column('n_folds', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('backtest_equity',
    sa.Column('backtest_id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('equity', forecaster.db.types.MoneyColumn, nullable=False),
    sa.Column('cash', forecaster.db.types.MoneyColumn, nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('benchmark_equity', forecaster.db.types.MoneyColumn, nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('backtest_id', 'ts')
    )
    op.create_table('backtest_trades',
    sa.Column('id', forecaster.db.types.BigIntPK, autoincrement=True, nullable=False),
    sa.Column('backtest_id', forecaster.db.types.UUIDColumn, nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('pnl', forecaster.db.types.MoneyColumn, nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('costs', forecaster.db.types.MoneyColumn, nullable=True),
    sa.Column('exit_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_backtest_id'), ['backtest_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_backtest_id'))

    op.drop_table('backtest_trades')
    op.drop_table('backtest_equity')
    op.drop_table('run_metrics')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_run_id'))
        batch_op.drop_index('idx_pred_lookup')

    op.drop_table('predictions')
    with op.batch_alter_table('fold_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fold_metrics_run_id'))

    op.drop_table('fold_metrics')
    op.drop_table('feature_importance')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_model_run_id'))

    op.drop_table('backtest_runs')
    op.drop_table('universe_members')
    op.drop_table('ohlcv_intraday')
    with op.batch_alter_table('ohlcv_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_ohlcv_ts')

    op.drop_table('ohlcv_daily')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index('idx_news_lookup')

    op.drop_table('news_articles')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_status'))
        batch_op.drop_index(batch_op.f('ix_model_runs_model_name'))
        batch_op.drop_index(batch_op.f('ix_model_runs_instrument_id'))
        batch_op.drop_index('idx_runs_lookup')

    op.drop_table('model_runs')
    op.drop_table('macro_observations')
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamentals_report_date'))

    op.drop_table('fundamentals')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_instrument_id'))

    op.drop_table('corporate_actions')
    op.drop_table('universes')
    op.drop_table('macro_series')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_tier'))
        batch_op.drop_index(batch_op.f('ix_instruments_symbol'))
        batch_op.drop_index(batch_op.f('ix_instruments_sector'))
        batch_op.drop_index('idx_instruments_tier_active')
        batch_op.drop_index('idx_instruments_name')

    op.drop_table('instruments')
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_log_symbol'))
        batch_op.drop_index(batch_op.f('ix_ingestion_log_provider'))

    op.drop_table('ingestion_log')
    op.drop_table('feature_sets')
    op.drop_table('api_quota')
    # ### end Alembic commands ###
